# == Class: tomcat
#
# This module installs the Tomcat application server from available repositories on RHEL variants
#
# === Parameters:
#
# [*version*]
#   tomcat full version number (valid format: x.y.z)
# [*package_name*]
#   tomcat package name
# [*service_name*]
#   tomcat service name
# [*service_ensure*]
#   whether the service should be running (valid: 'stopped'|'running')
# [*service_enable*]
#   enable service (boolean)
# [*tomcat_native*]
#   install tomcat native library (boolean)
# [*tomcat_native_package_name*]
#   tomcat native library package name
# [*extras*]
#   install extra libraries (boolean)
# [*admin_webapps*]
#   install admin webapps (boolean)
# [*admin_webapps_package_name*]
#   admin webapps package name
# [*create_default_admin*]
#   create default admin user (boolean)
# [*admin_user*]
#   admin user name
# [*admin_password*]
#   admin user password
#
# see README file for a description of all parameters related to server configuration
#
# === Actions:
#
# * Install tomcat
# * Configure main instance
# * Download extra libraries (optional)
#
# === Requires:
#
# * puppetlabs/stdlib module
# * puppetlabs/concat module
#
# === Sample Usage:
#
#  class { '::tomcat':
#    version      => '7.0.54',
#    service_name => 'tomcat7'
#  }
#
class tomcat (
  #
  # undef values are automatically generated within the class for convenience reasons
  #
  #----------------------------------------------------------------------------------
  # packages and service
  #----------------------------------------------------------------------------------
  $version                    = $::tomcat::params::version,
  $package_name               = $::tomcat::params::package_name,
  $service_name               = undef,
  $service_ensure             = 'running',
  $service_enable             = true,
  $tomcat_native              = false,
  $tomcat_native_package_name = $::tomcat::params::tomcat_native_package_name,
  $extras                     = false,
  #----------------------------------------------------------------------------------
  # security and administration
  #----------------------------------------------------------------------------------
  $admin_webapps              = true,
  $admin_webapps_package_name = undef,
  $create_default_admin       = true,
  $admin_user                 = 'tomcatadmin',
  $admin_password             = 'password',
  #----------------------------------------------------------------------------------
  # server configuration
  #----------------------------------------------------------------------------------
  $control_port        = 8005,
  # executors
  $threadpool_executor = false,
  # http connector
  $http_connector      = true,
  $http_port           = 8080,
  $use_threadpool      = false,
  #----------------------------------------------------------------------------------
  # ssl connector
  $ssl_connector = false,
  $ssl_port      = 8443,
  #----------------------------------------------------------------------------------
  # ajp connector
  $ajp_connector = true,
  $ajp_port      = 8009,
  #----------------------------------------------------------------------------------
  # engine
  $jvmroute = undef,
  #----------------------------------------------------------------------------------
  # host
  $hostname            = 'localhost',
  $autodeploy          = true,
  $deployOnStartup     = true,
  $undeployoldversions = false,
  $unpackwars          = true,
  #----------------------------------------------------------------------------------
  # valves
  $singlesignon_valve = false,
  $accesslog_valve    = true,
  #----------------------------------------------------------------------------------
  # jmx
  $jmx_listener      = false,
  $jmx_registry_port = 8050,
  $jmx_server_port   = 8051,
  $jmx_bind_address  = '',
  #----------------------------------------------------------------------------------
  # global configuration file
  #----------------------------------------------------------------------------------
  $catalina_base    = undef,
  $catalina_home    = undef,
  $jasper_home      = undef,
  $catalina_tmpdir  = undef,
  $catalina_pid     = undef,
  $java_home        = undef,
  $java_opts        = '-server',
  $catalina_opts    = undef,
  $security_manager = false,
  $tomcat_user      = undef,
  $tomcat_group     = undef,
  $lang             = undef,
  $shutdown_wait    = 30,
  $shutdown_verbose = false,
  $custom_fragment  = undef,
  #----------------------------------------------------------------------------------
  # logging
  #----------------------------------------------------------------------------------
  $log4j              = false,
  $log4j_package_name = $::tomcat::params::log4j_package_name,
  $log4j_conf_type    = 'ini',
  $log4j_conf_source  = "puppet:///modules/${module_name}/log4j.properties") inherits tomcat::params {
  # autogenerated defaults
  if $service_name == undef {
    $service_name_real = $package_name
  } else {
    $service_name_real = $service_name
  }

  if $admin_webapps_package_name == undef {
    $admin_webapps_package_name_real = $::osfamily ? {
      'RedHat' => "${package_name}-admin-webapps",
      default  => "${package_name}-admin"
    } } else {
    $admin_webapps_package_name_real = $admin_webapps_package_name
  }

  if $catalina_base == undef {
    $catalina_base_real = $::osfamily ? {
      'RedHat' => "/usr/share/${service_name_real}",
      default  => "/var/lib/${service_name_real}"
    } } else {
    $catalina_base_real = $catalina_base
  }

  if $catalina_home == undef {
    $catalina_home_real = $::osfamily ? {
      'RedHat' => $catalina_base_real,
      default  => "/usr/share/${service_name_real}"
    } } else {
    $catalina_home_real = $catalina_home
  }

  if $jasper_home == undef {
    $jasper_home_real = $catalina_home_real
  } else {
    $jasper_home_real = $jasper_home
  }

  if $catalina_tmpdir == undef {
    $catalina_tmpdir_real = "${catalina_home_real}/temp"
  } else {
    $catalina_tmpdir_real = $catalina_tmpdir
  }

  if $catalina_pid == undef {
    $catalina_pid_real = "/var/run/${service_name_real}.pid"
  } else {
    $catalina_pid_real = $catalina_pid
  }

  if $tomcat_user == undef {
    $tomcat_user_real = $::osfamily ? {
      'RedHat' => 'tomcat',
      default  => $package_name
    } } else {
    $tomcat_user_real = $tomcat_user
  }

  if $tomcat_group == undef {
    $tomcat_group_real = $tomcat_user_real
  } else {
    $tomcat_group_real = $tomcat_group
  }

  # get major version
  $array_version = split($version, '[.]')
  $maj_version = $array_version[0]
  $min_version = $array_version[1] * 100 + $array_version[2]

  # should we force download extras libs?
  if $log4j or $jmx_listener {
    $extras_real = true
  } else {
    $extras_real = $extras
  }

  # start the real action
  include tomcat::install
  include tomcat::service

  class { 'tomcat::config':
    require => Class['::tomcat::install'],
    notify  => Class['::tomcat::service']
  }

  Class['::tomcat::install'] ~>
  Class['::tomcat::service']

  if $log4j {
    class { 'tomcat::log4j':
      require => Class['::tomcat::install'],
      notify  => Class['::tomcat::service']
    }
  }

  if $extras_real {
    class { 'tomcat::extras':
      require => Class['::tomcat::install'],
      notify  => Class['::tomcat::service']
    }
  }
}